'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddUpdateOrganizationUserControl
    
    '''<summary>
    '''upAddUpdateOrganization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAddUpdateOrganization As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divHiddenFieldsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHiddenFieldsSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hdfForeignAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfForeignAddress As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfDepartmentSelectView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfDepartmentSelectView As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''divOrganizationForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOrganizationForm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''OrganizationInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrganizationInformation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divOrganizationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOrganizationID As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtEIDSSOrganizationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEIDSSOrganizationID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAbbreviation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAbbreviation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOrganizationName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrganizationName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlAccessoryCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccessoryCode As Global.EIDSSControlLibrary.DropDownList
    
    '''<summary>
    '''ddlOrganizationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOrganizationType As Global.EIDSSControlLibrary.DropDownList
    
    '''<summary>
    '''txtOrderNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNumber As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''ddlidfsHumanGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsHumanGender As Global.EIDSSControlLibrary.DropDownList
    
    '''<summary>
    '''chkForeignAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkForeignAddress As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Location As Global.EIDSS.HorizontalLocationUserControl
    
    '''<summary>
    '''divForeignAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divForeignAddress As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtForeignAddressString control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForeignAddressString As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Departments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Departments As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDepartments As Global.EIDSSControlLibrary.GridView
    
    '''<summary>
    '''divSelectablePreviewDepartmentList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSelectablePreviewDepartmentList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvDepartmentReviewList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDepartmentReviewList As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''OrganizationSideBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrganizationSideBar As Global.EIDSSControlLibrary.SideBarNavigation
    
    '''<summary>
    '''sbiOrganizationInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbiOrganizationInformation As Global.EIDSSControlLibrary.SideBarItem
    
    '''<summary>
    '''sbiDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbiDepartments As Global.EIDSSControlLibrary.SideBarItem
    
    '''<summary>
    '''sbiOrganizationReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbiOrganizationReview As Global.EIDSSControlLibrary.SideBarItem
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnPreviousSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousSection As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNextSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextSection As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelYes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdfOrganizationPanelController control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfOrganizationPanelController As Global.System.Web.UI.WebControls.HiddenField
End Class
