'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddUpdateTestUserControl
    
    '''<summary>
    '''divHiddenFieldsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHiddenFieldsSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hdfRecordID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfRecordID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfRecordAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfRecordAction As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfIdentity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdentity As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfDiseaseID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfDiseaseID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfTestCategoryTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTestCategoryTypeID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfTestsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTestsCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfSiteID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSiteID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfOrganizationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfOrganizationID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfPersonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPersonID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfUserFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUserFirstName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfUserLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUserLastName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''upAddUpdateTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAddUpdateTest As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divAddUpdateTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAddUpdateTest As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtDiseaseName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiseaseName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlTestNameTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestNameTypeID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtTestNameTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTestNameTypeName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlTestStatusTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestStatusTypeID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtTestStatusTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTestStatusTypeName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlTestResultTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestResultTypeID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtStartedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartedDate As Global.EIDSSControlLibrary.CalendarInput
    
    '''<summary>
    '''cvStartedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvStartedDate As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''txtResultDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResultDate As Global.EIDSSControlLibrary.CalendarInput
    
    '''<summary>
    '''cvResultDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvResultDate As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''txtTestCategoryTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTestCategoryTypeName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlTestedByPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestedByPerson As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtTestedByPersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTestedByPersonName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtResultsEnteredByPersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResultsEnteredByPersonName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtValidatedByPersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValidatedByPersonName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkExternalResultsIndicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExternalResultsIndicator As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtResultsReceivedByPersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResultsReceivedByPersonName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceivedDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtContactPersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactPersonName As Global.System.Web.UI.WebControls.TextBox
End Class
