'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddUpdateBatchUserControl
    
    '''<summary>
    '''divHiddenFieldsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHiddenFieldsSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hdfIdentity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdentity As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfSiteID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSiteID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfPersonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPersonID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfFirstName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfLastName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfOrganizationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfOrganizationID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfOrganizationName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfOrganizationName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfBatchTestTestTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfBatchTestTestTypeID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfFormTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfFormTypeID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfDiagnosisID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfDiagnosisID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfCountryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCountryID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''upAddUpdateBatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAddUpdateBatch As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''hdfObservationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfObservationID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfFormTemplateID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfFormTemplateID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''divEIDSSBatchID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEIDSSBatchID As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtEIDSSBatchTestID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEIDSSBatchTestID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBatchTestTestNameTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBatchTestTestNameTypeName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divTestResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTestResult As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlTestResultTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestResultTypeID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rfvTestResultTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTestResultTypeID As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlTestedByPersonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestedByPersonID As Global.EIDSSControlLibrary.DropDownList
    
    '''<summary>
    '''rfvTestedByPersonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTestedByPersonID As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''btnLookupEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLookupEmployee As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCreateEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateEmployee As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtTestStartedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTestStartedDate As Global.EIDSSControlLibrary.CalendarInput
    
    '''<summary>
    '''txtResultDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResultDate As Global.EIDSSControlLibrary.CalendarInput
    
    '''<summary>
    '''cvResultDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvResultDate As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''LUC08FlexFormTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LUC08FlexFormTemplate As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlLUC08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLUC08 As Global.System.Web.UI.WebControls.Panel
End Class
