'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BasicSyndromicSurveillance

    '''<summary>
    '''personalInformationSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents personalInformationSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlNotificationOf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNotificationOf As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlNameofHospital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNameofHospital As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReport As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMiddleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMiddleName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDoB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDoB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lucBasic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lucBasic As Global.EIDSS.LocationUserControl

    '''<summary>
    '''txtPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''symptomsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents symptomsSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtDateofSymptomOnset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateofSymptomOnset As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfPregnant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPregnant As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfPostPartum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPostPartum As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfFever38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfFever38 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlMethodofMeasurement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMethodofMeasurement As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtOtherMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherMethod As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''coughYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coughYes As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''coughNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coughNo As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''coughUnknown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coughUnknown As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''hdfCough control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCough As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''shortnessofBreathYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents shortnessofBreathYes As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''shortnessofBreathNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents shortnessofBreathNo As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''shortnessofBreathUnknown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents shortnessofBreathUnknown As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''hdfShortnessofBreath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfShortnessofBreath As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''seasonalFluVaccineYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents seasonalFluVaccineYes As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''seasonalFluVaccineNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents seasonalFluVaccineNo As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''seasonalFluVaccineUnknown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents seasonalFluVaccineUnknown As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''hdfSeasonalFluVaccine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSeasonalFluVaccine As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfAntiviralMedication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAntiviralMedication As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtNameofMedication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameofMedication As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDateReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateReceived As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblConcurrentConditions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConcurrentConditions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cblConcurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblConcurrent As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''samplesSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents samplesSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSampleCollection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSampleCollection As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSampleID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSampleID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTestResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestResults As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResult As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sbnPanelList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbnPanelList As Global.EIDSSControlLibrary.SideBarNavigation

    '''<summary>
    '''sbiPersonalInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbiPersonalInformation As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''sbiSymptoms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbiSymptoms As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''sbiSamples control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbiSamples As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''sbiReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbiReview As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdnPanelController control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPanelController As Global.System.Web.UI.WebControls.HiddenField
End Class
