'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PersonSearch

    '''<summary>
    '''uppPersonSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uppPersonSearch As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hdfCurform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCurform As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''searchForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchForm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ltxtEIDSSIDNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltxtEIDSSIDNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lddlidfsPersonIdType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lddlidfsPersonIdType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ltxtstrPersonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltxtstrPersonID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ltxtstrFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltxtstrFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMiddleInit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMiddleInit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ltxtstrSecondName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltxtstrSecondName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ltxtstrLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltxtstrLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSuffix As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ltxtdatDateOfBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltxtdatDateOfBirth As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''lddlidfsHumanGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lddlidfsHumanGender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lucSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lucSearch As Global.EIDSS.LocationUserControl

    '''<summary>
    '''ltxtidfsRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltxtidfsRegion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ltxtidfsRayon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltxtidfsRayon As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''alertMessageVSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alertMessageVSS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAlertMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnalertMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnalertMessage As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''searchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnEditSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditSearch As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblSearchCritIDType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritIDType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchCritPersonalID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritPersonalID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchCritEIDSSID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritEIDSSID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchCritFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritFirstName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchCritMiddleInit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritMiddleInit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchCritLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritLastName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchCritSuffixValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritSuffixValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchCritDoB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritDoB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchCritGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritGender As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchCritCitizenship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritCitizenship As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchCritRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritRegion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSearchCritRayon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchCritRayon As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvPeople control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPeople As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnNewPatient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewPatient As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNewSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''patient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents patient As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''personInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents personInformation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlidfsPersonIDType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsPersonIDType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtstrPersonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrPersonID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtstrFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtstrSecondName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrSecondName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtstrLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlidfsSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsSuffix As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtdatDateofBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatDateofBirth As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''txtReportedAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReportedAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlReportAgeUOMID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReportAgeUOMID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlidfsHumanGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsHumanGender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlidfsNationality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsNationality As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtstrPassportNbr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrPassportNbr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfisEmployeeFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfisEmployeeFlag As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtstrEmployerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrEmployerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdatEmployerLastDateAppeared control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatEmployerLastDateAppeared As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''txtstrEmployerCountryCodeandNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrEmployerCountryCodeandNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlidfsEmployerPhoneType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsEmployerPhoneType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdfstrEmployerPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfstrEmployerPhone As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''employerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents employerAddress As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lucEmployer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lucEmployer As Global.EIDSS.LocationUserControl

    '''<summary>
    '''hdfblnCurrentlyInSchool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfblnCurrentlyInSchool As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtstrSchoolName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrSchoolName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdatSchoolLastDateAppeared control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatSchoolLastDateAppeared As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''txtstrSchoolCountryCodeandNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrSchoolCountryCodeandNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlidfsSchoolPhoneType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsSchoolPhoneType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdfstrSchoolPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfstrSchoolPhone As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lucSchool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lucSchool As Global.EIDSS.LocationUserControl

    '''<summary>
    '''txtstrSchoolBuilding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrSchoolBuilding As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfidfEmployerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfidfEmployerAddress As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfidfRegistrationAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfidfRegistrationAddress As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfidfPatientAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfidfPatientAddress As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfidfSchoolAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfidfSchoolAddress As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''personalAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents personalAddress As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lucAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lucAddress As Global.EIDSS.LocationUserControl

    '''<summary>
    '''hdfAnotherAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAnotherAddress As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lucOtherAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lucOtherAddress As Global.EIDSS.LocationUserControl

    '''<summary>
    '''txtstrCountryCodeandNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrCountryCodeandNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlidfsPhoneType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsPhoneType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdfstrPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfstrPhone As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfstrAnotherPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfstrAnotherPhone As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtstrOtherCountryCodeandNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrOtherCountryCodeandNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlidfsOtherPhoneType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsOtherPhoneType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdfstrOtherPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfstrOtherPhone As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sideBarPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sideBarPanel As Global.EIDSSControlLibrary.SideBarNavigation

    '''<summary>
    '''sideBarItemPersonInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sideBarItemPersonInfo As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''sideBarItemPersonAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sideBarItemPersonAddress As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''sideBarItemPersonReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sideBarItemPersonReview As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnPreviousSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPreviousSection As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnNextSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextSection As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''patientReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents patientReview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkEditPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkEditPerson As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbldatEnteredDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldatEnteredDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldatModificationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldatModificationDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPatientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatientName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblstrPersonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstrPersonID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblstrPersonIDType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstrPersonIDType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPassportNbr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPassportNbr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldatDateofBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldatDateofBirth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReportedAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportedAge As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGender As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCitizenship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCitizenship As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPatientAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatientAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPatientPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatientPhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPatientOtherAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatientOtherAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblstrHomePhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstrHomePhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNewDisease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewDisease As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''gvDisease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDisease As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnReturnToSearch2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReturnToSearch2 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnNewSearch2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewSearch2 As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''disease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents disease As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''diseaseReportSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents diseaseReportSummary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblReportID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDiagnosis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiagnosis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEIDSS_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEIDSS_ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReportStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCaseClassification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseClassification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateEntered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateEntered As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateLastUpdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateLastUpdated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''diseaseNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents diseaseNotification As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtidfsDiagnosis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidfsDiagnosis As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdatDateofDiagnosis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatDateofDiagnosis As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''txtdatDateofNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatDateofNotification As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''ddlPatientStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPatientStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNotificationSentby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNotificationSentby As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNotificationReceivedby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNotificationReceivedby As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlPersonCurrentLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPersonCurrentLocation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlHospitalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHospitalName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''otherLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents otherLocation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtOtherLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''symptoms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents symptoms As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtDateOfSymptomOnset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateOfSymptomOnset As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''ddlInitialCaseClassification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInitialCaseClassification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''gvSymptoms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSymptoms As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''facilityDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents facilityDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdfPatientPreviouslySought control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPatientPreviouslySought As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtDateFirstSoughtCare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateFirstSoughtCare As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''txtFacilityFirstSoughtCare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilityFirstSoughtCare As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlNonNotifiableDiagnosis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNonNotifiableDiagnosis As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtdatDateofHospitalization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatDateofHospitalization As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''txtdatDateofDischarge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatDateofDischarge As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''txtHospitalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHospitalName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfhospitalization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfhospitalization As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''antibioticVaccineHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents antibioticVaccineHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdfAntibioticAntiviral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAntibioticAntiviral As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtstrAntibioticName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrAntibioticName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDose As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlDoseMeasurements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDoseMeasurements As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDateAntibioticFirstAdministered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateAntibioticFirstAdministered As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''txtAntibioticComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAntibioticComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfVaccine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfVaccine As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtstrVaccinationName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrVaccinationName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDateofVaccination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateofVaccination As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''samples control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents samples As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''caseDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caseDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtInvestigationNameOrganization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvestigationNameOrganization As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStartDateofInvestigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartDateofInvestigation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfRelatedToOutbreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfRelatedToOutbreak As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtCaseInvestigationOutbreakID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCaseInvestigationOutbreakID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfLocationofExposureKnown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfLocationofExposureKnown As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtDateofPotentialExposure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateofPotentialExposure As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''hdfExposureAddressType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfExposureAddressType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lucExposure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lucExposure As Global.EIDSS.LocationUserControl

    '''<summary>
    '''txtExposureLocationDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExposureLocationDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''riskFactors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents riskFactors As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvRisk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRisk As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hdfRiskFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfRiskFactor As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''finalOutcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents finalOutcome As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlFinalClassification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFinalClassification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDateofClassification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateofClassification As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''ddlOutcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOutcome As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDateofDeath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateofDeath As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''contactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contactList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SideBarNavigation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SideBarNavigation1 As Global.EIDSSControlLibrary.SideBarNavigation

    '''<summary>
    '''sideBarItemDiseaseNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sideBarItemDiseaseNotification As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''sideBarItemCaseDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sideBarItemCaseDetails As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''sideBarItemRiskFactors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sideBarItemRiskFactors As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''sideBarItemFinalOutcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sideBarItemFinalOutcome As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''sideBarItemContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sideBarItemContactList As Global.EIDSSControlLibrary.SideBarItem

    '''<summary>
    '''btn_Submit_Disease_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Submit_Disease_Report As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_Return_to_Person_Record control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Return_to_Person_Record As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtstrContactFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrContactFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtstrContactMiddleInit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrContactMiddleInit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtstrContactLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrContactLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlContactRelation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlContactRelation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtdatContactDoB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatContactDoB As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''ddlContactGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlContactGender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlContactCitizenship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlContactCitizenship As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtstrContactCountryCodeandNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrContactCountryCodeandNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlstrContactPhoneType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlstrContactPhoneType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdfstrContactPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfstrContactPhone As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lucContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lucContact As Global.EIDSS.LocationUserControl

    '''<summary>
    '''txtdatLastContactDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatLastContactDate As Global.EIDSSControlLibrary.CalendarInput

    '''<summary>
    '''txtPlaceofLastContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaceofLastContact As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdnPanelController control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPanelController As Global.System.Web.UI.WebControls.HiddenField
End Class
