'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard
    
    '''<summary>
    '''frmMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmMain As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''hdfSiteID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSiteID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfPersonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPersonID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUserID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUserName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfUserOrganization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUserOrganization As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfOrganizationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfOrganizationID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''gridCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hdfUnaccessionedSamplesCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUnaccessionedSamplesCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfUsersCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUsersCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfNotificationsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNotificationsCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfMyNotificationsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfMyNotificationsCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfInvestigationsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfInvestigationsCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfMyInvestigationsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfMyInvestigationsCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfMyCollectionsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfMyCollectionsCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''ucPageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucPageHeader As Global.EIDSS.PageHeader
    
    '''<summary>
    '''upDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDashboard As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''dashboardLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dashboardLinks As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''usersDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usersDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvUsers As Global.EIDSSControlLibrary.GridView
    
    '''<summary>
    '''divUsersPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUsersPager As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblUsersNumberOfRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsersNumberOfRecords As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUsersPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsersPageNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptUsersPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptUsersPager As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''unaccessionedSamplesDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents unaccessionedSamplesDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvUnaccessionedSamples control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvUnaccessionedSamples As Global.EIDSSControlLibrary.GridView
    
    '''<summary>
    '''divUnaccessionedSamplesPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUnaccessionedSamplesPager As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblUnaccessionedSamplesNumberofRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnaccessionedSamplesNumberofRecords As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUnaccessionedSamplesPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnaccessionedSamplesPageNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptUnaccessionedSamplesPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptUnaccessionedSamplesPager As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''approvalsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents approvalsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvMyApprovals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMyApprovals As Global.EIDSSControlLibrary.GridView
    
    '''<summary>
    '''notificationsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notificationsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvNotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvNotifications As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''divNotificationsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNotificationsPager As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblNotificationsNumberofRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotificationsNumberofRecords As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNotificationsPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotificationsPageNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptNotificationsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptNotificationsPager As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''mynotificationsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mynotificationsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvMyNotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMyNotifications As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''divMyNotificationsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMyNotificationsPager As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblMyNotificationsNumberofRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMyNotificationsNumberofRecords As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMyNotificationsPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMyNotificationsPageNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptMyNotificationsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMyNotificationsPager As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''investigationsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents investigationsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvInvestigations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvInvestigations As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''divInvestigationsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInvestigationsPager As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblInvestigationsNumberofRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvestigationsNumberofRecords As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInvestigationsPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvestigationsPageNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptInvestigationsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptInvestigationsPager As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''myinvestigationsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myinvestigationsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvMyInvestigations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMyInvestigations As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''divMyInvestigationsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMyInvestigationsPager As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblMyInvestigationsNumberofRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMyInvestigationsNumberofRecords As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMyInvestigationsPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMyInvestigationsPageNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptMyInvestigationsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMyInvestigationsPager As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''myCollectionsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myCollectionsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvMyCollections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMyCollections As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''divMyCollectionsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMyCollectionsPager As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblMyCollectionsNumberofRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMyCollectionsNumberofRecords As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMyCollectionsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMyCollectionsPager As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptMyCollectionsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMyCollectionsPager As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lbl_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Error As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnErrorOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnErrorOK As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblstrFinalDiagnosis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstrFinalDiagnosis As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbldatDateOfDiagnosis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldatDateOfDiagnosis As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbldatNotificationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldatNotificationDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblstrFinalState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstrFinalState As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblstrNotificationSentby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstrNotificationSentby As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblstrNotificationReceivedby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstrNotificationReceivedby As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblstrHospitalizationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstrHospitalizationStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblstrHospital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstrHospital As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblstrCurrentLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstrCurrentLocation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnNotificationsOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNotificationsOK As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''veterinaryDiseaseNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents veterinaryDiseaseNotification As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblReportedByOrganization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportedByOrganization As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblReportedByPersonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportedByPersonID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblReportDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInvestigatedByOrganizationName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvestigatedByOrganizationName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInvestigatedByPersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvestigatedByPersonName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAssignedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAssignedDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInvestigationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvestigationDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSiteName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSiteName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEnteredByPersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnteredByPersonName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEnteredDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnteredDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnInvestigationsOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInvestigationsOK As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''ucPageFooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucPageFooter As Global.EIDSS.PageFooterUserControl
End Class
