'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GeneralError
    
    '''<summary>
    '''lblFriendlyErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFriendlyErrorMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlDetailedErrorPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDetailedErrorPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblErrorDetailedMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorDetailedMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblErrorHandler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorHandler As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInnerMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInnerMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInnerTrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInnerTrace As Global.System.Web.UI.WebControls.Label
End Class
