DECLARE @securityPolicyID bigint
	
	BEGIN TRANSACTION

	EXEC dbo.USP_GBL_NEXTKEYID_GET 'SecurityPolicyConfiguration', @securityPolicyID OUTPUT

	INSERT INTO SecurityPolicyConfiguration(
			 [SecurityPolicyConfigurationUID]
			,[MinPasswordLength]
			,[EnforcePasswordHistoryCount]
			,[MinPasswordAgeDays]
			,[ForceUppercaseFlag]
			,[ForceLowercaseFlag]
			,[ForceNumberUsageFlag]
			,[ForceSpecialCharactersFlag]
			,[AllowUseOfSpaceFlag]
			,[PreventSequentialCharacterFlag]
			,[PreventUsernameUsageFlag]
			,[LockoutThld]
			,[LockoutDurationMinutes]
			,[MaxSessionLength]
			,[SesnIdleTimeoutWarnThldMins]
			,[SesnIdleCloseoutThldMins]
			,[intRowStatus]
			--,[rowguid]
			,[AuditCreateUser]
			,[AuditCreateDTM]
			,[AuditUpdateUser]
			,[AuditUpdateDTM]
			--,[SourceSystemNameID]
			--,[SourceSystemKeyValue]
	)

	VALUES
	( 
		  @securityPolicyID
		, 8 -- min password length...
		,12 -- enforce history...
		,60 -- min age days...
		, 1 -- force uppercase...
		, 1 -- force lower...
		, 1 -- force number usage...
		, 1 -- force special chars...
		, 1 -- allow use of space...
		, 1 -- prevent sequential chars flag...
		, 1 -- prevent username...
		, 3 -- account lockout threshold...
		, 5 -- lockout duration ...
		, 2 -- session max length...
		,15 -- session inactivity timeout...
		, 5 -- session idle closeout...
		, 0 -- intRowStatus...
		--,NewID() -- rowguid...
		,'SYSTEM' -- audit create user...
		,GetDate() -- audit create...
		,'SYSTEM' -- audit update user...
		,GetDate() -- audit modify
	)

	IF @@TRANCOUNT > 0 
		COMMIT  
	ELSE 
		ROLLBACK