'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrganizationAdmin

    '''<summary>
    '''divHiddenFieldsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHiddenFieldsSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdfLangID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfLangID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfidfUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfidfUserID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfidfOrgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfidfOrgID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfidfLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfidfLocation As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfidfsSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfidfsSite As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfidfsRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfidfsRegion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfidfsRayon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfidfsRayon As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfintHACode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfintHACode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfUniqueOrgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUniqueOrgID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfOrgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfOrgName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfAbbreviation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAbbreviation As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfOfficeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfOfficeID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNew As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''upOrganizationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upOrganizationList As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''gvOrganizationList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOrganizationList As Global.EIDSSControlLibrary.GridView

    '''<summary>
    '''searchUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HdgSearchTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdgSearchTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtstrOrganizationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrOrganizationID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtstrOrgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrOrgName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtstrOrgFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstrOrgFullName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlSpecialization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSpecialization As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkShowForeignOrganizations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowForeignOrganizations As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LocationUserControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocationUserControl As Global.EIDSS.LocationUserControl

    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
End Class
