'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ParameterEditor
    
    '''<summary>
    '''parameterTypeQuestionEditorForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parameterTypeQuestionEditorForm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''UpdatePanelChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelChild As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divCrudButtonPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCrudButtonPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnksearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnksearch As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''mpe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpe As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''btnParameteradd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnParameteradd As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnsaveParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsaveParameter As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnEditParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditParameter As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnParameterCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnParameterCancel As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnDeleteParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteParameter As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnAddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddItem As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsave As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEdit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divHiddenFieldsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHiddenFieldsSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hdfLangID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfLangID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''TreeView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TreeView1 As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''hdnSectionId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSectionId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfformType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfformType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnidfsParentSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnidfsParentSection As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tblcreatesection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblcreatesection As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''txtDefaultName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDefaultName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNationalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNationalName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''hdnidfsParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnidfsParameter As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnsectionidvalue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnsectionidvalue As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnformTypeid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnformTypeid As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnstrNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnstrNote As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tblParameterTypeQuestionEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblParameterTypeQuestionEditor As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''txtDefaultLongName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDefaultLongName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtParametrDefaultName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParametrDefaultName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtParameterNationalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParameterNationalName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtParametrNationalLongName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParametrNationalLongName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlParameterType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlParameterType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEditor As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlHACode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHACode As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtLabelSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabelSize As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlScheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlScheme As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHeight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWidth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divTemplatesUsedParameters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTemplatesUsedParameters As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblTemplatesCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTemplatesCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RptTemplatesUsedParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RptTemplatesUsedParameter As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlPopup1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopup1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtsectionsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsectionsearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtParametersearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParametersearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button
End Class
