'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VeterinaryActiveSurveillanceCampaign
    
    '''<summary>
    '''upHiddenFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upHiddenFields As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divHiddenFieldsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHiddenFieldsSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hdfCampaignID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCampaignID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfHasSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfHasSession As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfComments As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfCampaignModule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCampaignModule As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfRecordID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfRecordID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfRowAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfRowAction As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfIdentity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdentity As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfAvianOrLivestock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAvianOrLivestock As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfWarningMessageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfWarningMessageType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfMonitoringSessionCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfMonitoringSessionCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''upSearchCampaign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upSearchCampaign As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlSearchForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearchForm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''divCampaignSearchForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCampaignSearchForm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCampaignSearchCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCampaignSearchCriteria As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''toggleIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents toggleIcon As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtSearchEIDSSCampaignID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchEIDSSCampaignID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSearchCampaignName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchCampaignName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlSearchCampaignTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchCampaignTypeID As Global.EIDSSControlLibrary.DropDownList
    
    '''<summary>
    '''ddlSearchCampaignStatusTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchCampaignStatusTypeID As Global.EIDSSControlLibrary.DropDownList
    
    '''<summary>
    '''ddlSearchDiseaseID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchDiseaseID As Global.EIDSSControlLibrary.DropDownList
    
    '''<summary>
    '''txtSearchStartDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchStartDateFrom As Global.EIDSSControlLibrary.CalendarInput
    
    '''<summary>
    '''txtSearchStartDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchStartDateTo As Global.EIDSSControlLibrary.CalendarInput
    
    '''<summary>
    '''cpvStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpvStartDate As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''btnCancelSearchCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSearchCriteria As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''upCampaignSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCampaignSearchResults As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divCampaignSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCampaignSearchResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hdfSearchCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSearchCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''gvCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCampaigns As Global.EIDSSControlLibrary.GridView
    
    '''<summary>
    '''divCampaignsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCampaignsPager As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblCampaignsRecordCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCampaignsRecordCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCampaignsPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCampaignsPageNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptCampaignsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCampaignsPager As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnCancelSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSearchResults As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPrintSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintSearchResults As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddCampaign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddCampaign As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''upAddUpdateCampaign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAddUpdateCampaign As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divVeterinaryActiveSurveillanceCampaignForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divVeterinaryActiveSurveillanceCampaignForm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''upCampaignInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCampaignInformation As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''hdgCampaignInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdgCampaignInformation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtEIDSSCampaignID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEIDSSCampaignID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCampaignName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCampaignName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlCampaignTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCampaignTypeID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlCampaignStatusTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCampaignStatusTypeID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCampaignStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCampaignStartDate As Global.EIDSSControlLibrary.CalendarInput
    
    '''<summary>
    '''cmvFutureCampaignStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmvFutureCampaignStartDate As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''txtCampaignEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCampaignEndDate As Global.EIDSSControlLibrary.CalendarInput
    
    '''<summary>
    '''cmvCampaignDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmvCampaignDate As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''cmvFutureCampaignEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmvFutureCampaignEndDate As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''txtCampaignAdministrator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCampaignAdministrator As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlDiseaseID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDiseaseID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''divSpeciesAndSamplesContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSpeciesAndSamplesContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvSpeciesAndSamples control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSpeciesAndSamples As Global.EIDSSControlLibrary.GridView
    
    '''<summary>
    '''upInsertSpeciesToSampleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upInsertSpeciesToSampleType As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlInsertSpeciesTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInsertSpeciesTypeID As Global.EIDSSControlLibrary.DropDownList
    
    '''<summary>
    '''ddlInsertSampleTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInsertSampleTypeID As Global.EIDSSControlLibrary.DropDownList
    
    '''<summary>
    '''txtInsertPlannedNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsertPlannedNumber As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''txtInsertComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsertComments As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnNewSpeciesToSampleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewSpeciesToSampleType As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divSessionsContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSessionsContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSearchMonitoringSessions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchMonitoringSessions As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnAddMonitoringSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddMonitoringSession As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''gvMonitoringSessions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMonitoringSessions As Global.EIDSSControlLibrary.GridView
    
    '''<summary>
    '''divMonitoringSessionsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMonitoringSessionsPager As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblMonitoringSessionsRecordCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonitoringSessionsRecordCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMonitoringSessionsPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonitoringSessionsPageNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptMonitoringSessionsPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMonitoringSessionsPager As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''divConclusionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConclusionContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtConclusion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConclusion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnCancelAddUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAddUpdate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ucSearchVeterinarySession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucSearchVeterinarySession As Global.EIDSS.SearchVeterinarySessionUserControl
    
    '''<summary>
    '''upSuccessModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upSuccessModal As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblSuccessMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAddUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAddUpdate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnReturnToCampaign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReturnToCampaign As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnReturnToDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReturnToDashboard As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divSuccessOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSuccessOK As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''upWarningModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upWarningModal As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''hdgWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdgWarning As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''warningSubTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents warningSubTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divWarningBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divWarningBody As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divWarningYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divWarningYesNo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnWarningModalYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWarningModalYes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnWarningModalNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWarningModalNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divWarningOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divWarningOK As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''upErrorModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upErrorModal As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''hdgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdgError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''errorSubTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errorSubTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divErrorBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divErrorBody As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
