'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AgeGroupStatisticalAgeGroupMatrix
    
    '''<summary>
    '''upAgeGroupStatisticalAgeGroupMatrix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAgeGroupStatisticalAgeGroupMatrix As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlidfsDiagnosisAgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsDiagnosisAgeGroup As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAgeGroupStatisticalAgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgeGroupStatisticalAgeGroup As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvAgeGroupStatisticalAgeGroupMatrix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAgeGroupStatisticalAgeGroupMatrix As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sampleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sampleType As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlidfsStatisticalAgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsStatisticalAgeGroup As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAddStatisticalAgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddStatisticalAgeGroup As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''hdfAGSAGValidationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAGSAGValidationError As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfAGSAGidfDiagnosisAgeGroupToStatisticalAgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAGSAGidfDiagnosisAgeGroupToStatisticalAgeGroup As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSubmitAgeGroupStatisticalAgeGroupMatrix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitAgeGroupStatisticalAgeGroupMatrix As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelAgeGroupStatisticalAgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAgeGroupStatisticalAgeGroup As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''ageGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ageGroup As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtAGstrDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAGstrDefault As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAGstrName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAGstrName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAGintLowerBoundary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAGintLowerBoundary As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''txtAGintUpperBoundary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAGintUpperBoundary As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''ddlAGidfsAgeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAGidfsAgeType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAGintOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAGintOrder As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''hdfAGValidationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAGValidationError As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfAGidfsAgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAGidfsAgeGroup As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSubmitAgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitAgeGroup As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelAgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAgeGroup As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''txtSAGstrDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSAGstrDefault As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSAGstrName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSAGstrName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSAGintOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSAGintOrder As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''hdfSAGValidationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSAGValidationError As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSubmitStatisticalAgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitStatisticalAgeGroup As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelStatisticalAgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelStatisticalAgeGroup As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Error As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnErrorOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnErrorOK As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSuccessOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSuccessOK As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Delete As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Cancel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnCancelYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Cancel_Reference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Cancel_Reference As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnCancelReferenceYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelReferenceYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelReferenceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelReferenceNo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Continue_Required control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Continue_Required As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnContinueRequiredYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinueRequiredYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnContinueRequiredNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinueRequiredNo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Already_Exists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Already_Exists As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnAlreadyExistsYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlreadyExistsYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnAlreadyExistsNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlreadyExistsNo As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
