'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SampleTypeDerivativeMatrix
    
    '''<summary>
    '''upSampleTypeDerivative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upSampleTypeDerivative As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnAddSampleTypeDerivativeMatrix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSampleTypeDerivativeMatrix As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvSampleTypeDerivativeMatrix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSampleTypeDerivativeMatrix As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sampleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sampleType As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlidfsSampleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsSampleType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAddSampleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSampleType As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''ddlidfsDerivative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsDerivative As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAddDerivative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDerivative As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''hdfSTDValidationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSTDValidationError As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfSTDidfSampleTypeForDerivative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSTDidfSampleTypeForDerivative As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSubmitSampleTypeDerivative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitSampleTypeDerivative As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelSampleTypeDerivative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSampleTypeDerivative As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''txtSTstrDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSTstrDefault As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSTstrName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSTstrName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSTstrSampleCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSTstrSampleCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lstSTHACode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSTHACode As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtSTintOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSTintOrder As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''hdfSTValidationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSTValidationError As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSubmitSampleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitSampleType As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelSampleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSampleType As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''txtDstrDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDstrDefault As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDstrName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDstrName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDstrCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDstrCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lstDHACode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstDHACode As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtDintOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDintOrder As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''hdfDValidationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfDValidationError As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSubmitDerivative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitDerivative As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelDerivative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelDerivative As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Error As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnErrorOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnErrorOK As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSuccessOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSuccessOK As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Delete As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Cancel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnCancelYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Cancel_Reference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Cancel_Reference As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnCancelReferenceYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelReferenceYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelReferenceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelReferenceNo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Continue_Required control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Continue_Required As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnContinueRequiredYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinueRequiredYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnContinueRequiredNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinueRequiredNo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Already_Exists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Already_Exists As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnAlreadyExistsYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlreadyExistsYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnAlreadyExistsNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlreadyExistsNo As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
