'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TestToTestResultMatrix
    
    '''<summary>
    '''upDiseaseAgeGroupMatrix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDiseaseAgeGroupMatrix As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''rblTestResultsRelations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTestResultsRelations As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''ddlidfsTestName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsTestName As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAddTestName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddTestName As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnAddTestTestResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddTestTestResult As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvTestToTestResultMatrix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTestToTestResultMatrix As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''ddlidfsTestResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlidfsTestResult As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAddTestResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddTestResult As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''chkblnIndicative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkblnIndicative As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''hdfTTRValidationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTTRValidationError As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfTTRidfsTestName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTTRidfsTestName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfTTRidfsTestResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTTRidfsTestResult As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSubmitTestTestResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitTestTestResult As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelTestTestResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelTestTestResult As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''txtTNstrDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTNstrDefault As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTNstrName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTNstrName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lstTNHACode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstTNHACode As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtTNintOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTNintOrder As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''hdfTNValidationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTNValidationError As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSubmitTestName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitTestName As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelTestName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelTestName As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''txtTRstrDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTRstrDefault As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTRstrName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTRstrName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lstTRHACode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstTRHACode As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtTRintOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTRintOrder As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''hdfTRValidationError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTRValidationError As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSubmitTestResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitTestResult As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelTestResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelTestResult As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Error As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnErrorOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnErrorOK As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSuccessOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSuccessOK As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Delete As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnDeleteYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Cancel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnCancelYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Cancel_Reference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Cancel_Reference As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnCancelReferenceYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelReferenceYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCancelReferenceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelReferenceNo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Continue_Required control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Continue_Required As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnContinueRequiredYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinueRequiredYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnContinueRequiredNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinueRequiredNo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lbl_Already_Exists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Already_Exists As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnAlreadyExistsYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlreadyExistsYes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnAlreadyExistsNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlreadyExistsNo As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
