CREATE TABLE [dbo].[SecurityPolicyConfiguration] (
    [SecurityPolicyConfigurationUID] INT              NOT NULL,
    [MinPasswordLength]              INT              NULL,
    [EnforcePasswordHistoryCount]    INT              NULL,
    [MinPasswordAgeDays]             INT              NULL,
    [ForceUppercaseFlag]             BIT              NULL,
    [ForceLowercaseFlag]             BIT              NULL,
    [ForceNumberUsageFlag]           BIT              NULL,
    [ForceSpecialCharactersFlag]     BIT              NULL,
    [AllowUseOfSpaceFlag]            BIT              NULL,
    [PreventSequentialCharacterFlag] BIT              NULL,
    [PreventUsernameUsageFlag]       BIT              NULL,
    [LockoutThld]                    INT              NULL,
    [LockoutDurationMinutes]         INT              NULL,
    [MaxSessionLength]               INT              NULL,
    [SesnIdleTimeoutWarnThldMins]    INT              NULL,
    [SesnIdleCloseoutThldMins]       INT              NULL,
    [intRowStatus]                   INT              CONSTRAINT [Def_SecurityPolicyConfiguration_intRowStatus] DEFAULT ((0)) NOT NULL,
    [rowguid]                        UNIQUEIDENTIFIER CONSTRAINT [DF_SecurityPolicyConfiguration_rowguid] DEFAULT (newsequentialid()) ROWGUIDCOL NOT NULL,
    [AuditCreateUser]                VARCHAR (100)    CONSTRAINT [DF__SecurityPolicyConfiguration__AuditCreateUSer] DEFAULT (user_name()) NOT NULL,
    [AuditCreateDTM]                 DATETIME         CONSTRAINT [DF__SecurityPolicyConfiguration__AuditCreateDTM] DEFAULT (getdate()) NOT NULL,
    [AuditUpdateUser]                VARCHAR (100)    CONSTRAINT [DF__SecurityPolicyConfiguration__AuditUpdateUser] DEFAULT (user_name()) NOT NULL,
    [AuditUpdateDTM]                 DATETIME         NULL,
    [SourceSystemNameID]             BIGINT           NULL,
    [SourceSystemKeyValue]           NVARCHAR (MAX)   NULL,
    CONSTRAINT [XPKSecurityPolicy] PRIMARY KEY CLUSTERED ([SecurityPolicyConfigurationUID] ASC),
    CONSTRAINT [FK_SecurityPolicyConfig_trtBaseReference_SourceSystemNameID] FOREIGN KEY ([SourceSystemNameID]) REFERENCES [dbo].[trtBaseReference] ([idfsBaseReference])
);

