'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SystemPreferences
    
    '''<summary>
    '''canvasUpdatePreferences control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents canvasUpdatePreferences As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMain As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''ddlStartupLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStartupLanguage As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCountry As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlBarcodePrinter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBarcodePrinter As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlDocumentPrinter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDocumentPrinter As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''fuEPIInfoPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuEPIInfoPath As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lblEPIInfoPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEPIInfoPath As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlDefaultMapProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDefaultMapProject As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tblAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblAdditional As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''chkShowTextInToolbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowTextInToolbar As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowWarning As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowSaveDataPrompt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowSaveDataPrompt As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkPrintVetrinaryMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPrintVetrinaryMap As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowNavigatorInH02Form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowNavigatorInH02Form As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowStarForBlank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowStarForBlank As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkLabModuleSimplifiedMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLabModuleSimplifiedMode As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFilterSamplesByDiag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFilterSamplesByDiag As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkDefaultRegionInSearchPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDefaultRegionInSearchPanel As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowWarningForFinalCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowWarningForFinalCase As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''uccDefualtNumberofDaysDisplayed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uccDefualtNumberofDaysDisplayed As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''buttonCollection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonCollection As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
