'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SecurityPolicy
    
    '''<summary>
    '''canvasSecurityPolicy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents canvasSecurityPolicy As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblPasswordPolicy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPasswordPolicy As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''idfSecurityConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents idfSecurityConfiguration As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtintPasswordMinimalLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtintPasswordMinimalLength As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''txtintPasswordHistoryLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtintPasswordHistoryLength As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''txtintPasswordAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtintPasswordAge As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''chkintForcePasswordComplexity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkintForcePasswordComplexity As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''tblLockoutPolicy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblLockoutPolicy As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''txtintAccountTryCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtintAccountTryCount As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''txtintAccountLockTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtintAccountLockTimeout As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''txtintInactivityTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtintInactivityTimeout As Global.EIDSSControlLibrary.NumericSpinner
    
    '''<summary>
    '''buttonCollection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonCollection As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As NormalView
        Get
            Return CType(MyBase.Master, NormalView)
        End Get
    End Property
End Class
