CREATE TYPE [dbo].[TestTableType] AS TABLE (
    [TestID]                        BIGINT         NOT NULL,
    [TestNameTypeID]                BIGINT         NULL,
    [TestCategoryTypeID]            BIGINT         NULL,
    [TestResultTypeID]              BIGINT         NULL,
    [TestStatusTypeID]              BIGINT         NOT NULL,
    [DiseaseID]                     BIGINT         NOT NULL,
    [SampleID]                      BIGINT         NULL,
    [BatchTestID]                   BIGINT         NULL,
    [TestNumber]                    INT            NULL,
    [Note]                          NVARCHAR (500) NULL,
    [RowStatus]                     INT            NOT NULL,
    [StartedDate]                   DATETIME       NULL,
    [ConcludedDate]                 DATETIME       NULL,
    [TestedByOrganizationID]        BIGINT         NULL,
    [TestedByPersonID]              BIGINT         NULL,
    [ResultEnteredByOrganizationID] BIGINT         NULL,
    [ResultEnteredByPersonID]       BIGINT         NULL,
    [ValidatedByOrganizationID]     BIGINT         NULL,
    [ValidatedByPersonID]           BIGINT         NULL,
    [ReadOnlyIndicator]             BIT            NOT NULL,
    [NonLaboratoryTestIndicator]    BIT            NOT NULL,
    [ExternalTestIndicator]         BIT            NULL,
    [PerformedByOrganizationID]     BIGINT         NULL,
    [ReceivedDate]                  DATETIME       NULL,
    [ContactPersonName]             NVARCHAR (200) NULL,
    [MaintenanceFlag]               NVARCHAR (20)  NULL,
    [RecordAction]                  NCHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([TestID] ASC));

