CREATE TYPE [dbo].[tlbHdrMaterialGetListSPType] AS TABLE (
    [idfHumanCase]              BIGINT           NULL,
    [idfMaterial]               BIGINT           NOT NULL,
    [strBarcode]                NVARCHAR (200)   NULL,
    [strFieldBarcode]           NVARCHAR (200)   NULL,
    [idfsSampleType]            BIGINT           NOT NULL,
    [strSampleTypeName]         NVARCHAR (2000)  NULL,
    [datFieldCollectionDate]    DATETIME         NULL,
    [idfSendToOffice]           BIGINT           NULL,
    [strSendToOffice]           NVARCHAR (2000)  NULL,
    [idfFieldCollectedByOffice] BIGINT           NULL,
    [strFieldCollectedByOffice] NVARCHAR (2000)  NULL,
    [datFieldSentDate]          DATETIME         NULL,
    [strNote]                   NVARCHAR (500)   NULL,
    [datAccession]              DATETIME         NULL,
    [idfsAccessionCondition]    BIGINT           NULL,
    [strCondition]              NVARCHAR (200)   NULL,
    [idfsRegion]                BIGINT           NULL,
    [strRegionName]             NVARCHAR (300)   NULL,
    [idfsRayon]                 BIGINT           NULL,
    [strRayonName]              NVARCHAR (300)   NULL,
    [blnAccessioned]            INT              NULL,
    [RecordAction]              VARCHAR (1)      NULL,
    [idfsSampleKind]            BIGINT           NULL,
    [SampleKindTypeName]        NVARCHAR (2000)  NULL,
    [idfsSampleStatus]          BIGINT           NULL,
    [SampleStatusTypeName]      NVARCHAR (2000)  NULL,
    [idfFieldCollectedByPerson] BIGINT           NULL,
    [datSampleStatusDate]       DATETIME         NULL,
    [sampleGuid]                UNIQUEIDENTIFIER NOT NULL,
    [intRowStatus]              INT              NOT NULL);

