CREATE TYPE [dbo].[tlbHdrTestGetListSPType] AS TABLE (
    [idfHumanCase]              BIGINT           NULL,
    [idfMaterial]               BIGINT           NULL,
    [strBarcode]                NVARCHAR (200)   NULL,
    [strFieldBarcode]           NVARCHAR (200)   NULL,
    [idfsSampleType]            BIGINT           NULL,
    [strSampleTypeName]         NVARCHAR (2000)  NULL,
    [datFieldCollectionDate]    DATETIME         NULL,
    [idfSendToOffice]           BIGINT           NULL,
    [strSendToOffice]           NVARCHAR (2000)  NULL,
    [idfFieldCollectedByOffice] BIGINT           NULL,
    [strFieldCollectedByOffice] NVARCHAR (2000)  NULL,
    [datFieldSentDate]          DATETIME         NULL,
    [idfsSampleKind]            BIGINT           NULL,
    [SampleKindTypeName]        NVARCHAR (2000)  NULL,
    [idfsSampleStatus]          BIGINT           NULL,
    [SampleStatusTypeName]      NVARCHAR (2000)  NULL,
    [idfFieldCollectedByPerson] BIGINT           NULL,
    [datSampleStatusDate]       DATETIME         NULL,
    [sampleGuid]                UNIQUEIDENTIFIER NULL,
    [idfTesting]                BIGINT           NULL,
    [idfsTestName]              BIGINT           NULL,
    [idfsTestCategory]          BIGINT           NULL,
    [idfsTestResult]            BIGINT           NULL,
    [idfsTestStatus]            BIGINT           NULL,
    [idfsDiagnosis]             BIGINT           NULL,
    [strTestStatus]             NVARCHAR (2000)  NULL,
    [strTestResult]             NVARCHAR (2000)  NULL,
    [name]                      NVARCHAR (2000)  NULL,
    [datReceivedDate]           DATETIME         NULL,
    [datConcludedDate]          DATETIME         NULL,
    [idfTestedByPerson]         BIGINT           NULL,
    [idfTestedByOffice]         BIGINT           NULL,
    [idfsInterpretedStatus]     BIGINT           NULL,
    [strInterpretedComment]     NVARCHAR (2000)  NULL,
    [datInterpretedDate]        DATETIME         NULL,
    [strInterpretedBy]          NVARCHAR (2000)  NULL,
    [blnValidateStatus]         BIT              NULL,
    [strValidateComment]        NVARCHAR (2000)  NULL,
    [datValidationDate]         DATETIME         NULL,
    [strValidatedBy]            NVARCHAR (2000)  NULL,
    [strAccountName]            NVARCHAR (2000)  NULL,
    [testGuid]                  UNIQUEIDENTIFIER NULL,
    [intRowStatus]              INT              NULL);

