CREATE TYPE [dbo].[tlbMonitoringSessionSummaryGetListSPType] AS TABLE (
    [idfMonitoringSessionSummary] BIGINT         NOT NULL,
    [idfMonitoringSession]        BIGINT         NOT NULL,
    [idfFarm]                     BIGINT         NOT NULL,
    [strFarmCode]                 NVARCHAR (200) NULL,
    [idfSpecies]                  BIGINT         NULL,
    [SpeciesTypeName]             NVARCHAR (200) NULL,
    [idfsAnimalSex]               BIGINT         NULL,
    [AnimalGenderTypeName]        NVARCHAR (200) NULL,
    [intSampledAnimalsQty]        INT            NULL,
    [intSamplesQty]               INT            NULL,
    [datCollectionDate]           DATETIME       NULL,
    [intPositiveAnimalsQty]       INT            NULL,
    [intRowStatus]                INT            NOT NULL,
    [strMaintenanceFlag]          NVARCHAR (20)  NULL,
    [idfsSampleType]              BIGINT         NULL,
    [SampleTypeName]              NVARCHAR (200) NULL,
    [SampleChecked]               BIT            NULL,
    [idfsDiagnosis]               BIGINT         NULL,
    [DiagnosisName]               NVARCHAR (200) NULL,
    [DiagnosisChecked]            BIT            NULL,
    [RecordAction]                NCHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([idfMonitoringSessionSummary] ASC));

