CREATE TYPE [dbo].[tlbMaterialGetListSPType] AS TABLE (
    [idfMaterial]                      BIGINT         NOT NULL,
    [idfsSampleType]                   BIGINT         NOT NULL,
    [SampleTypeName]                   NVARCHAR (200) NULL,
    [idfRootMaterial]                  BIGINT         NULL,
    [idfParentMaterial]                BIGINT         NULL,
    [idfHuman]                         BIGINT         NULL,
    [HumanName]                        NVARCHAR (200) NULL,
    [idfSpecies]                       BIGINT         NULL,
    [SpeciesTypeName]                  NVARCHAR (200) NULL,
    [idfAnimal]                        BIGINT         NULL,
    [strAnimalCode]                    NVARCHAR (200) NULL,
    [idfsAnimalGender]                 BIGINT         NULL,
    [AnimalGenderTypeName]             NVARCHAR (200) NULL,
    [idfsAnimalAge]                    BIGINT         NULL,
    [AnimalAgeTypeName]                NVARCHAR (200) NULL,
    [strColor]                         NVARCHAR (200) NULL,
    [idfMonitoringSession]             BIGINT         NULL,
    [idfFieldCollectedByPerson]        BIGINT         NULL,
    [FieldCollectedByPersonName]       NVARCHAR (200) NULL,
    [idfFieldCollectedByOffice]        BIGINT         NULL,
    [FieldCollectedByOfficeSiteName]   NVARCHAR (200) NULL,
    [idfMainTest]                      BIGINT         NULL,
    [intTestNumber]                    BIGINT         NULL,
    [datFieldCollectionDate]           DATETIME       NULL,
    [datFieldSentDate]                 DATETIME       NULL,
    [strFieldBarcode]                  NVARCHAR (200) NULL,
    [strCalculatedCaseID]              NVARCHAR (200) NULL,
    [strCalculatedHumanName]           NVARCHAR (700) NULL,
    [idfVectorSurveillanceSession]     BIGINT         NULL,
    [idfVector]                        BIGINT         NULL,
    [idfSubdivision]                   BIGINT         NULL,
    [strNameChars]                     NVARCHAR (200) NULL,
    [idfsSampleStatus]                 BIGINT         NULL,
    [SampleStatusTypeName]             NVARCHAR (200) NULL,
    [idfInDepartment]                  BIGINT         NULL,
    [InDepartmentSiteName]             NVARCHAR (200) NULL,
    [idfDestroyedByPerson]             BIGINT         NULL,
    [DestroyedByPersonName]            NVARCHAR (200) NULL,
    [datEnteringDate]                  DATETIME       NULL,
    [datDestructionDate]               DATETIME       NULL,
    [strBarcode]                       NVARCHAR (200) NULL,
    [strNote]                          NVARCHAR (500) NULL,
    [idfsSite]                         BIGINT         NOT NULL,
    [MaterialSiteName]                 NVARCHAR (200) NULL,
    [intRowStatus]                     INT            NOT NULL,
    [idfSendToOffice]                  BIGINT         NULL,
    [SendToOfficeSiteName]             NVARCHAR (200) NULL,
    [blnReadOnly]                      BIT            NOT NULL,
    [idfsBirdStatus]                   BIGINT         NULL,
    [BirdStatusTypeName]               NVARCHAR (200) NULL,
    [idfHumanCase]                     BIGINT         NULL,
    [idfVetCase]                       BIGINT         NULL,
    [datAccession]                     DATETIME       NULL,
    [idfsAccessionCondition]           BIGINT         NULL,
    [AccessionConditionTypeName]       NVARCHAR (200) NULL,
    [strCondition]                     NVARCHAR (200) NULL,
    [idfAccesionByPerson]              BIGINT         NULL,
    [AccessionByPersonName]            NVARCHAR (200) NULL,
    [idfsDestructionMethod]            BIGINT         NULL,
    [DestructionMethodTypeName]        NVARCHAR (200) NULL,
    [idfsCurrentSite]                  BIGINT         NULL,
    [CurrentSiteName]                  NVARCHAR (200) NULL,
    [idfsSampleKind]                   BIGINT         NULL,
    [SampleKindTypeName]               NVARCHAR (200) NULL,
    [blnAccessioned]                   BIT            NULL,
    [blnShowInCaseOrSession]           BIT            NULL,
    [blnShowInLabList]                 BIT            NULL,
    [blnShowInDispositionList]         BIT            NULL,
    [blnShowInAccessionInForm]         BIT            NULL,
    [idfMarkedForDispositionByPerson]  BIGINT         NULL,
    [MarkedForDispositionByPersonName] NVARCHAR (200) NULL,
    [datOutOfRepositoryDate]           DATETIME       NULL,
    [datSampleStatusDate]              DATETIME       NULL,
    [strMaintenanceFlag]               NVARCHAR (20)  NULL,
    [idfFarm]                          BIGINT         NULL,
    [strFarmCode]                      NVARCHAR (200) NULL,
    [RecordAction]                     NCHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([idfMaterial] ASC));

