CREATE TYPE [dbo].[tlbTestingGetListSPType] AS TABLE (
    [idfTesting]                    BIGINT         NOT NULL,
    [idfsTestName]                  BIGINT         NULL,
    [TestNameTypeName]              NVARCHAR (200) NULL,
    [idfsTestCategory]              BIGINT         NULL,
    [TestCategoryTypeName]          NVARCHAR (200) NULL,
    [idfsTestResult]                BIGINT         NULL,
    [TestResultTypeName]            NVARCHAR (200) NULL,
    [idfsTestStatus]                BIGINT         NOT NULL,
    [TestStatusTypeName]            NVARCHAR (200) NULL,
    [idfsDiagnosis]                 BIGINT         NOT NULL,
    [DiagnosisName]                 NVARCHAR (200) NULL,
    [idfMaterial]                   BIGINT         NULL,
    [strFieldBarcode]               NVARCHAR (200) NULL,
    [strBarCode]                    NVARCHAR (200) NULL,
    [SampleTypeName]                NVARCHAR (200) NULL,
    [idfSpecies]                    BIGINT         NULL,
    [SpeciesTypeName]               NVARCHAR (200) NULL,
    [idfAnimal]                     BIGINT         NULL,
    [strAnimalCode]                 NVARCHAR (200) NULL,
    [idfBatchTest]                  BIGINT         NULL,
    [idfObservation]                BIGINT         NOT NULL,
    [intTestNumber]                 INT            NULL,
    [strNote]                       NVARCHAR (500) NULL,
    [intRowStatus]                  INT            NOT NULL,
    [datStartedDate]                DATETIME       NULL,
    [datConcludedDate]              DATETIME       NULL,
    [idfTestedByOffice]             BIGINT         NULL,
    [TestedByOfficeSiteName]        NVARCHAR (200) NULL,
    [idfTestedByPerson]             BIGINT         NULL,
    [TestedByPersonName]            NVARCHAR (200) NULL,
    [idfResultEnteredByOffice]      BIGINT         NULL,
    [ResultEnteredByOfficeSiteName] NVARCHAR (200) NULL,
    [idfResultEnteredByPerson]      BIGINT         NULL,
    [ResultEnteredByPersonName]     NVARCHAR (200) NULL,
    [idfValidatedByOffice]          BIGINT         NULL,
    [ValidatedByOfficeSiteName]     NVARCHAR (200) NULL,
    [idfValidatedByPerson]          BIGINT         NULL,
    [ValidatedByPersonName]         NVARCHAR (200) NULL,
    [blnReadOnly]                   BIT            NOT NULL,
    [blnNonLaboratoryTest]          BIT            NOT NULL,
    [blnExternalTest]               BIT            NULL,
    [idfPerformedByOffice]          BIGINT         NULL,
    [PerformedByOfficeSiteName]     NVARCHAR (200) NULL,
    [datReceivedDate]               DATETIME       NULL,
    [strContactPerson]              NVARCHAR (200) NULL,
    [strMaintenanceFlag]            NVARCHAR (20)  NULL,
    [idfFarm]                       BIGINT         NULL,
    [strFarmCode]                   NVARCHAR (200) NULL,
    [RecordAction]                  NCHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([idfTesting] ASC));

