CREATE TYPE [dbo].[tlbVectorSummaryGetListSPType] AS TABLE (
    [RecordID]                                BIGINT         NOT NULL,
    [idfsVSSessionSummary]                    BIGINT         NULL,
    [idfDiagnosisVectorSurveillanceSession]   BIGINT         NULL,
    [strVSSessionSummaryID]                   NVARCHAR (200) NULL,
    [DiagnosisidfGeoLocation]                 BIGINT         NULL,
    [lucSummaryCollectionidfsResidentType]    BIGINT         NULL,
    [lucSummaryCollectionidfsGroundType]      BIGINT         NULL,
    [lucSummaryCollectionidfsGeolocationType] BIGINT         NULL,
    [lucSummaryCollectionidfsCountry]         BIGINT         NULL,
    [lucSummaryCollectionidfsRegion]          BIGINT         NULL,
    [lucSummaryCollectionidfsRayon]           BIGINT         NULL,
    [lucSummaryCollectionidfsSettlement]      BIGINT         NULL,
    [lucSummaryCollectionstrApartment]        NVARCHAR (200) NULL,
    [lucSummaryCollectionstrBuilding]         NVARCHAR (200) NULL,
    [lucSummaryCollectionstrStreetName]       NVARCHAR (200) NULL,
    [lucSummaryCollectionstrHouse]            NVARCHAR (200) NULL,
    [lucSummaryCollectionstrPostCode]         NVARCHAR (200) NULL,
    [lucSummaryCollectionstrDescription]      NVARCHAR (200) NULL,
    [lucSummaryCollectiondblDistance]         FLOAT (53)     NULL,
    [lucSummaryCollectionstrLatitude]         FLOAT (53)     NULL,
    [lucSummaryCollectionstrLongitude]        FLOAT (53)     NULL,
    [lucSummaryCollectiondblAccuracy]         FLOAT (53)     NULL,
    [lucSummaryCollectiondblAlignment]        FLOAT (53)     NULL,
    [blnForeignAddress]                       BIT            NULL,
    [strForeignAddress]                       NVARCHAR (200) NULL,
    [blnGeoLocationShared]                    BIT            NULL,
    [datSummaryCollectionDateTime]            DATETIME       NULL,
    [SummaryInfoSpecies]                      BIGINT         NULL,
    [SummaryInfoSex]                          BIGINT         NULL,
    [PoolsVectors]                            BIGINT         NULL,
    [RecordAction]                            NCHAR (1)      NOT NULL,
    PRIMARY KEY CLUSTERED ([RecordID] ASC));

