CREATE TYPE [dbo].[tlbVectorGetListSPType] AS TABLE (
    [RecordID]                              BIGINT         NOT NULL,
    [idfVector]                             BIGINT         NULL,
    [idfsDetailedVectorSurveillanceSession] BIGINT         NULL,
    [idfHostVector]                         BIGINT         NULL,
    [strVectorID]                           NVARCHAR (50)  NULL,
    [strFieldVectorID]                      NVARCHAR (50)  NULL,
    [idfDetailedLocation]                   BIGINT         NULL,
    [intDetailedElevation]                  INT            NULL,
    [DetailedSurroundings]                  BIGINT         NULL,
    [strGEOReferenceSource]                 NVARCHAR (500) NULL,
    [idfCollectedByOffice]                  BIGINT         NULL,
    [idfCollectedByPerson]                  BIGINT         NULL,
    [datCollectionDateTime]                 DATETIME       NULL,
    [idfsCollectionMethod]                  BIGINT         NULL,
    [idfsBasisOfRecord]                     BIGINT         NULL,
    [idfDetailedVectorType]                 BIGINT         NULL,
    [idfsVectorSubType]                     BIGINT         NULL,
    [intQuantity]                           INT            NULL,
    [idfsSex]                               BIGINT         NULL,
    [idfIdentIFiedByOffice]                 BIGINT         NULL,
    [idfIdentIFiedByPerson]                 BIGINT         NULL,
    [datIdentIFiedDateTime]                 DATETIME       NULL,
    [idfsIdentIFicationMethod]              BIGINT         NULL,
    [idfObservation]                        BIGINT         NULL,
    [idfsFormTemplate]                      BIGINT         NULL,
    [idfsDayPeriod]                         BIGINT         NULL,
    [strComment]                            NVARCHAR (500) NULL,
    [idfsEctoparASitesCollected]            BIGINT         NULL,
    [RecordAction]                          NCHAR (1)      NOT NULL,
    PRIMARY KEY CLUSTERED ([RecordID] ASC));

